apiVersion: apps/v1
kind: Deployment
metadata:
  name: lecture
  labels:
    app: lecture
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lecture
  template:
    metadata:
      labels:
        app: lecture
    spec:
      containers:
        - name: lecture
          image: username/lecture:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5